name: AntiGriefingPlugin
version: '${project.version}'
main: com.hotamachi.antigriefingplugin.AntiGriefingPlugin
api-version: 1.21
author: hotamachisubaru 2024-2025
commands:
  reload:
    description: 設定ファイルをリロードします。
    usage: /reload
    permission: reload.permission
  world:
    description: 個別ワールド別に設定します。
    usage: /world <world>
    permission: world.permission
  antigrief:
    description: ゲーム内でプラグインの有効化と無効化を切替します。
    usage: /antigrief
  antinuker:
    description: nuker対策の有効化と無効化を切り替えします。
    usage: /antinuker
  baninfo:
    description: 指定したプレイヤーが BAN されているかどうかを確認し、理由を表示します。
    usage: /baninfo <playername>
  reload.permission:
    description: リロード権限
    default: op
  world.permission:
    description: ワールド別権限
    default: op
