name: AntiGriefingPlugin
version: '${project.version}'
main: com.hotamachi.antigriefingplugin.AntiGriefingPlugin
api-version: 1.21
author: hotamachisubaru 2024
depend:
  - AdvancedBan
commands:
  reload:
    description: 設定ファイルをリロードします。
    usage: /reload
    permission: reload.permission
  toggleworld:
    description: 個別ワールド別に設定します。
    usage: /toggleworld <world>
    permission: toggleworld.permission
  toggleantigrief:
    description: ゲーム内でプラグインの有効化と無効化を切替します。
    usage: /toggleantigrief
    permission: toggleantigrief.permission
permissions:
  reload.permission:
    description: リロード権限
    default: op
  toggleworld.permission:
    description: ワールド別権限
    default: op
  toggleantigrief.permission:
    description: 切替権限
    default: op