name: AntiGriefingPlugin
version: '${project.version}'
main: com.hotamachi.antigriefingplugin.AntiGriefingPlugin
api-version: 1.21
author: hotamachisubaru 2024
depend:
  - AdvancedBan
commands:
  reload:
    description: 設定ファイルをリロードします。
    usage: /reload
    permission: reload.permission
  world:
    description: 個別ワールド別に設定します。
    usage: /toggleworld <world>
    permission: toggleworld.permission
  antigrief:
    description: ゲーム内でプラグインの有効化と無効化を切替します。
    usage: /antigrief
  permissions:
  reload.permission:
    description: リロード権限
    default: op
  world.permission:
    description: ワールド別権限
    default: op
